# Generated by Django 4.1.3 on 2022-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('web_page_link', models.URLField()),
                ('photo', models.URLField()),
            ],
        ),
    ]
